### ISSUE TITLE
feat: 차량 현황 조회

### ISSUE THREAD

**Issue by woohyeoung** [4team-final/server#14]
## 💡 Issue
각 분류별 차량 목록 조회

## 📝 todo
- [x] 차량 전체 예약 현황 조회
- [x] 차량 전체 미예약 현황 조회
- [x] 차량 종류에 따른 예약 현황 조회
- [x] 특정 날짜 + 특정 시간별 차량 예약 현황 조회
- [x] 내 예약 조회 과거
- [x] 내 예약 조회 현재
- [x] 7일 동안 가장 많이 예약된 차량 조회
- [x] 7일 동안 가장 많이 예약된 시간대 조회
- [x] 최근에 예약된 차량 조회
- [x] 내가 즐겨찾기한 차량 조회
- [x] 즐겨찾기가 많은 차량 TOP3 조회
