### ISSUE TITLE
feat: 차량 예약 수정 및 삭제

### ISSUE THREAD

**Issue by woohyeoung** [4team-final/server#19]
## 💡 Issue
유저 및 관리자의 각 역할별 차량 예약 수정 및 삭제

## 📝 todo
- [x] 차량 예약 수정 - 유저
- [x] 차량 예약 삭제 - 유저
- [x] 즐겨찾기 차량 삭제 - 유저
