### ISSUE TITLE
Feat: 회의실 예약 현황 조회

### ISSUE THREAD

**Issue by jaebin1234** [4team-final/server#23]
## 💡 Issue
회의실 목록별 예약 조회

## 📝 todo
--- 윤성
- [x] 회의실 전체 예약/미예약 조회
- [x] 회의실 호수에 따른 예약 현황 조회
- [x] 특정 날짜 + 특정 시간별 예약 현황 조회
- [x] 즐겨찾기가 많은 회의실 TOP3 조회
- [x] 내가 즐겨찾기한 회의실 조희
