### ISSUE TITLE
feat: 차량 등록, 수정, 삭제

### ISSUE THREAD

**Issue by woohyeoung** [4team-final/server#38]
## 💡 Issue
관리자가 예약을 진행할 차량 등록, 수정, 삭제

## 📝 todo
- [x] 차량 정보 등록
- [x] 차량 정보 수정
- [x] 차량 정보 삭제
